import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = resolve(ROOT, "src");
const LIB = resolve(ROOT, "lib");

/** Every shipped image is inlined: the plugin never loads a remote asset. */
const ASSETS = [
  ["XIAO_STANDING_DATA_URI", "assets/character/xiao-standing.webp", "image/webp"],
  ["XIAO_COMPANION_DATA_URI", "assets/companion/xiao-companion.webp", "image/webp"],
  ["XIAO_COMPANION_MARK_DATA_URI", "assets/companion/xiao-companion-mark.webp", "image/webp"],
  ["XIAO_NUO_MASK_DATA_URI", "assets/ornaments/nuo-mask-mark.webp", "image/webp"],
  ["XIAO_CELEBRATION_DATA_URI", "assets/showcase/celebration-card.webp", "image/webp"],
];

async function generateAssetsModule() {
  const lines = ["// Generated by scripts/build.mjs from assets/. Do not edit manually."];
  for (const [name, relativePath, mime] of ASSETS) {
    const bytes = await readFile(resolve(ROOT, relativePath));
    lines.push(`export const ${name} = ${JSON.stringify(`data:${mime};base64,${bytes.toString("base64")}`)};`);
  }
  lines.push("");
  await writeFile(resolve(SRC, "client/assets.generated.js"), lines.join("\n"), "utf8");
}

async function generateStylesModule() {
  const css = (await readFile(resolve(SRC, "client/styles.css"), "utf8")).trim();
  const source = [
    "// Generated by scripts/build.mjs from src/client/styles.css. Do not edit manually.",
    `export const XIAO_STYLE_TEXT = ${JSON.stringify(css)};`,
    "",
  ].join("\n");
  await writeFile(resolve(SRC, "client/styles.generated.js"), source, "utf8");
}

async function generateVersionModule() {
  const packageJson = JSON.parse(await readFile(resolve(ROOT, "package.json"), "utf8"));
  const source = [
    "// Generated by scripts/build.mjs from package.json. Do not edit manually.",
    `export const PLUGIN_VERSION = ${JSON.stringify(packageJson.version)};`,
    "",
  ].join("\n");
  await writeFile(resolve(SRC, "client/version.generated.js"), source, "utf8");
}

async function buildHost() {
  await build({
    entryPoints: [resolve(SRC, "host/index.js")],
    outfile: resolve(LIB, "index.js"),
    bundle: true,
    format: "esm",
    platform: "node",
    target: "node22",
    external: ["@deepseek-ai/schemastery"],
    treeShaking: true,
    minify: false,
    sourcemap: false,
    legalComments: "none",
    charset: "utf8",
    logLevel: "warning",
  });
}

async function buildClient() {
  const result = await build({
    entryPoints: [resolve(SRC, "client/index.js")],
    bundle: true,
    format: "cjs",
    platform: "browser",
    target: ["chrome120"],
    external: ["react", "react/jsx-runtime"],
    jsx: "automatic",
    treeShaking: true,
    minify: false,
    sourcemap: false,
    legalComments: "none",
    charset: "utf8",
    logLevel: "warning",
    write: false,
  });
  const bundle = result.outputFiles[0].text.trim();
  const indented = bundle.split("\n").map((line) => (line ? `\t\t${line}` : "")).join("\n");
  const output = [
    "window.__ModuleLoader__.load({",
    '\tid: "dsh-xiao-theme",',
    "\tfactory: (require) => {",
    "\t\tvar module = { exports: {} };",
    "\t\tvar exports = module.exports;",
    indented,
    "\t\treturn module.exports;",
    "\t}",
    "});",
    "",
  ].join("\n");
  await writeFile(resolve(LIB, "client.js"), output, "utf8");
}

await mkdir(LIB, { recursive: true });
await generateAssetsModule();
await generateStylesModule();
await generateVersionModule();
await Promise.all([buildHost(), buildClient()]);
console.log("Built the dsh-xiao-theme Host and Client bundles with esbuild.");
